apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    name: hello
spec:
  containers:
  - name: hello
    image: gcr.io/PROJECT-ID/hello:1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080